language:
  java
jdk:
  - oraclejdk8
before_script:
  - sudo apt-get install -qq --force-yes mesa-utils libgl1-mesa-swx11 libgl1-mesa-swx11-dev xvfb  
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
script:
  mvn test
cache:
  directories:
  - .autoconf
  - $HOME/.m2
env:
  - MAVEN_OPTS=-Djava.library.path=target/natives