language:
  java
jdk:
  - oraclejdk8
env:
  - TRAVIS_CI=true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  mvn test -Ptrasis
cache:
  directories:
  - .autoconf
  - $HOME/.m2
env:
  - MAVEN_OPTS=-Djava.library.path=target/natives
